# Generated by Django 5.1.4 on 2025-01-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_card_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(max_length=75)),
                ('uid', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'User Details',
            },
        ),
    ]
