# Generated by Django 5.1.4 on 2025-01-10 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_firebaseuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cards',
        ),
        migrations.DeleteModel(
            name='FirebaseUser',
        ),
        migrations.AlterModelOptions(
            name='userdetails',
            options={},
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='displayName',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='display_name',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(default='N/A', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='uid',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
