# Generated by Django 5.1.4 on 2025-01-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userdetails_id_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='id_token',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
